### ISSUE TITLE
error: Illegal return statement

### ISSUE THREAD

**Issue by caoer** [Jianru-Lin/lambda-view#3]
running lambda-view against `https://github.com/patriksimek/vm2/blob/master/lib/sandbox.js#L13` 

got following error:

```
[10/2/2016 8:29:05 PM] INFO read file from "~~~~~~~~~/vm2/lib/sandbox.js"...
[10/2/2016 8:29:05 PM] INFO parsing javascript source code and generating html content...
[10/2/2016 8:29:05 PM] ERROR Line 13: Illegal return statement
~
```

**Comment by Jianru-Lin** [comment]
There is a return statement at line 13 in file `https://github.com/patriksimek/vm2/blob/master/lib/sandbox.js#L13`:

```
return ((vm, host) => {
    // ...
})
```

Because return statement is only valid in function body, however there isn't any function body surrounded it.

Actually `https://github.com/patriksimek/vm2/blob/master/lib/main.js` will load this file as plain text and generate a new string base on it before running:

```
const sb = fs.readFileSync (`${__dirname}/sandbox.js`, "utf8") ;
vm.runInContext (`(function (vm, host, Contextify, Decontextify, Buffer) { ${sb} \n})`, ...)
```

So, this is not a bug of lambda-view.

:)

**Comment by caoer** [comment]
@Jianru-Lin got it working now! thanks for the explanation. 👍
